<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Workflows\a7b3-ElGogh-API.json" />
    <None Remove="Workflows\animagineXL-ElGogh-API.json" />
    <None Remove="Workflows\AnythingXL-ElGogh-API.json" />
    <None Remove="Workflows\Automatic1111-ElGogh-API.json" />
    <None Remove="Workflows\aZovyaRPGArtistTools-ElGogh-API.json" />
    <None Remove="Workflows\Counterfeit-ElGogh-API.json" />
    <None Remove="Workflows\ElGoghV1-Anime-ElGogh-API.json" />
    <None Remove="Workflows\ElGoghV1-Fantasy-ElGogh-API.json" />
    <None Remove="Workflows\forRealXL-ElGogh-API.json" />
    <None Remove="Workflows\nightSkyYozoraStyle-ElGogh-API.json" />
    <None Remove="Workflows\ponyDiffusion-ElGogh-API.json" />
    <None Remove="Workflows\realisticVision-ElGogh-API.json" />
    <None Remove="Workflows\tmndMix-ElGogh-API.json" />
    <None Remove="Workflows\UnstableDiffusers-ElGogh-API.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Workflows\a7b3-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\animagineXL-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\AnythingXL-ElGogh-API.json" />
    <EmbeddedResource Include="Workflows\Automatic1111-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\aZovyaRPGArtistTools-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\Counterfeit-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\ElGoghV1-Anime-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\ElGoghV1-Fantasy-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\forRealXL-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\nightSkyYozoraStyle-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\ponyDiffusion-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\realisticVision-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\tmndMix-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Workflows\UnstableDiffusers-ElGogh-API.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net7.0\api_test_anime.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net7.0\api_example.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-01884" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="5.0.0-nightly-01884" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="5.0.0-nightly-01884" />
    <PackageReference Include="LiteDB.Async" Version="0.1.7" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.4" />
    <PackageReference Include="Websocket.Client" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
